### ISSUE TITLE
Re-train existing models with larger datasets

### ISSUE THREAD

**Issue by marco-c** [mozilla/translations#178]
Since we last trained our models, newer and larger datasets have been released. We should re-train them (possibly after fixing a few other quality bugs).

**Comment by eu9ene** [comment]
+ try using more monolingual data for back translations

**Comment by marco-c** [comment]
Could you file a separate issue for that for tracking purposes?

**Comment by eu9ene** [comment]
Sure, I added #181

**Comment by marco-c** [comment]
Closing as duplicate of #891.
