### ISSUE TITLE
Check training for CJK

### ISSUE THREAD

**Issue by eu9ene** [mozilla/translations#747]
Does it require any adjustment? Should we change any hyperparameters etc.?

**Comment by eu9ene** [comment]
Example training log from HPLT https://github.com/hplt-project/HPLT-MT-Models/blob/main/v1.0/training/en-zh_hant/hplt/model.train.log

**Comment by eu9ene** [comment]
I changed the vocabulary size to 64000 based on the HPLT config. I don't yet understand the implications.

**Comment by ZJaume** [comment]
Chinese should be trained in two different models, one for simplified and one for traditional, as it might be too large vocabulary to fit in 32k pieces.
