### ISSUE TITLE
Perform a comprehensive testing before the final reuploading

### ISSUE THREAD

**Issue by eu9ene** [mozilla/translations#793]
We've implemented a lot of fixes recently. Before the final reuploading, we should reupload several language pairs with different configurations and do a comprehensive check that everything is working as expected and that all the data is present and readable. 
It should include:
- uploading old Snakemake experiments from GCP
- uploading recent experiments from Taskcluster
- uploading archived Taskcluster experiments from GCP
- running the pipeline on Taskcluster to test the online mode

The goal is not to just run all those but also to carefully verify the results.

**Comment by vrigal** [comment]
@eu9ene I cleaned the teklia workspace on W&B, and reuploaded experiments:
* From the recent GCP archive you provided (Taskcluster)
* From the old GCP archive you provided (Snakemake)
* From a recent task group [Fv23lalyTfSfbmGx0YxypA](https://firefox-ci-tc.services.mozilla.com/tasks/groups/Fv23lalyTfSfbmGx0YxypA), with the recursive option.

I also tested with a newer task group [Pk0d9wH9Q96Q4U_lUwMnwQ](https://firefox-ci-tc.services.mozilla.com/tasks/groups/Pk0d9wH9Q96Q4U_lUwMnwQ) but had this error:
> [tracking WARNING] Task group ax-Cwm7TTDSXrQRPhC5tFA cannot be published to WandB: configuration missing @ extra/action/context/input

**Comment by eu9ene** [comment]
> [tracking WARNING] Task group ax-Cwm7TTDSXrQRPhC5tFA cannot be published to WandB: configuration missing @ extra/action/context/input
@vrigal hm, I'm not sure what this is about. Where exactly does it happen? Is it an error from W&B client or Taskcluster?

**Comment by vrigal** [comment]
@eu9ene It comes from the [parser](https://github.com/mozilla/firefox-translations-training/blob/main/tracking/translations_parser/cli/taskcluster_group.py#L205), because the task corresponding to the group is missing the `experiment` entry in its [task definition](https://firefox-ci-tc.services.mozilla.com/tasks/ax-Cwm7TTDSXrQRPhC5tFA/definition). Maybe it is an intended behavior ?

**Comment by eu9ene** [comment]
Ok, this task group is a pull request CI, so it doesn't have a train action. One of the newest manual runs is https://firefox-ci-tc.services.mozilla.com/tasks/groups/dzijiL-PQ4ScKBB3oIjGQg
