### ISSUE TITLE
Investigate switching to ICU segmenter

### ISSUE THREAD

**Issue by eu9ene** [mozilla/translations#860]
We currently use Moses tokenizer for alignments because it seems like it's a standard in the MT world and it's what OpusTrainer supports for detokenization (we will likely feed tokenized text to it to support CJK).

We should investigate switching to the ICU segmenter because we use it in Firefox during inference.

Greg:

> Two things that could be helpful here are the ICU segmenter (which is equivalent to the powerful Intl.Segmenter in javascript. I believe there are ICU bindings available in Python.
> 
> Tutorial: https://www.bedrick.org/notes/python-icu-bindings/
> 
> The other package is the unicodedata one, which gives you more information about codepoints.
> 
> https://docs.python.org/3/library/unicodedata.html
> 
> You can also write regexes using character properties.
> 
> It's also important to run normalization on the text (so the codepoints are all represented consistently), which I don't think the opus tools have done a good job using consistently.
> 
> I think we should lean in to our OpusCleaner fork for fixes here, and once we are done see if they want to accept any of our fixes.

**Comment by eu9ene** [comment]
A reminder od our goals here:

Input: 
- source and target text for each line in a parallel corpus

OpusTrainer's input:
- tokenized text (tokens are the whole words or punctuation). Tokens are split by a whitespace
- alignments information that matches the positions of the tokens

OpusTrainer's output (Marian's input): 
- source and target text with random noise inserted in the correct positions that match the translation
- alignments information that matches sentence piece tokenization performed by marian


I've done some experiments with tokenization/detokenization using [ICU segmenter](https://pypi.org/project/PyICU/), [opus-fast-mosestokenizer](https://github.com/Helsinki-NLP/opus-fast-mosestokenizer) that we use in the pipeline and [sacremoses](https://github.com/hplt-project/sacremoses/tree/master) detokenizer used by OpusTrainer.

[code](https://gist.github.com/eu9ene/b92e15653bd1728c2a7c82a3eaa19122)
[results](https://gist.github.com/eu9ene/71df37376fb6b284f7f90955e33d08e2)

Takeaways:
- ICU is good at tokenization for the languages I tried (ru, en, zh)
- Detokenization is a non-trivial problem and requires implementing language specific rules for punctuation (see [sacremoses detokenizer](https://github.com/hplt-project/sacremoses/blob/65543c34baf589f30260488d882d0060abaa4087/sacremoses/tokenize.py#L543))
- Moses tokenizer doesn't work properly with Chinese
- sacremoses detokenizer makes mistakes in complex punctuation that includes quotes for English and Russian, so Marian currently gets a text with some extra whitespace for those use cases

Potential solutions:

1. Use ICU for tokenization excluding whitespaces (similar to Moses, for example, `'Hello, world! ' -> ['Hello', ',', 'world', '!']`) and  continue using sacremoses for detokenization since it already have some languages specific rules. 
   **pros:** 
    - doesn't require touching OpusTrainer itself, only sacremoses update
    
   **cons:**
    - requires fixing support for CJK and fixing punctuation issues in sacremoses detokenizer
    - the text that we feed to marian will be slightly modified due to potential other punctuation issues and whitespace normalization
2. Use ICU for tokenization preserving whitespaces (for example, `'Hello, world! ' -> ['Hello', ',', ' ', 'world', '!', ' ']`)
   **pros:**
   - zero information loss on text reconstruction (basically just `"".join(tokens)` for all languages)
   - no need to support any custom detokenization rules anywhere
   
   **cons:**
   - a text file on disk would include spaces as spaces and spaces as separators at the same time which can still work
   - requires remapping alignments produced by eflomal which doesn't take spaces into account to the position of tokens with spaces. Spaces would not have any alignment information.
   - requires adding support for a custom detokenizer in OpusTrainer
   - not clear yet if OpusTrainer would require further modification, for example for the procedure of remapping alignments to sentence piece tokenization for marian


IMO the second solution is preferrable as it's more robust. @gregtatum @ZJaume what do you think?

**Comment by ZJaume** [comment]
Regarding the first solution, I have write permissions for sacremoses and could publish fixes if necessary. But yes, second option seems more robust. To kind of solve the problem of spaces, I'm wondering if a solution like SentencePiece does would do the trick: segment text with ICU preserving spaces, process the list of tokens and replace spaces by special token `▁` and then run the alignment step so spaces would have alignment information. This however could complicate things for OpusTrainer? But we already need to add a custom detokenizer? I'm not sure.

Do we really know that the Chinese segmentation that ICU is doing are actual words? Most of the segmenter I knew until know for Chinese were using Machine Learning methods, so my guess was that word segmentation in Chinese was not possible using only unicode properties (which is what ICU seems to be doing?).

**Comment by gregtatum** [comment]
It looks like only Thai and Burmese are using LSTMs for their "break iterator" which is the name of their segmenter on the ICU4C side.

https://github.com/unicode-org/icu/tree/06a23f8d37ce0c3a985bb676cbc05eb7bd5f3573/icu4c/source/data/brkitr/lstm

I see there is a [cjdict.txt](https://github.com/unicode-org/icu/blob/06a23f8d37ce0c3a985bb676cbc05eb7bd5f3573/icu4c/source/data/brkitr/dictionaries/cjdict.txt), so it looks like they are segmenting via a dictionary, not codepoints.

**Comment by eu9ene** [comment]
> process the list of tokens and replace spaces by special token ▁

Cool, I'll give it a try. I assume the probability of encoutering this token in the data is low. It's `b'\xe2\x96\x81'`

> Do we really know that the Chinese segmentation that ICU is doing are actual words?

Well, I looked at how it splits my test data a bit and the word separation made sense. I'm not 100% sure it's always perfect but maybe it's good enough for our purposes.

Ok, so I'll code the option 2 and see how it goes. It should be feasible. To make things faster I'll use OpusTrainer Mozilla fork initially, then we can push upstream. 

This is based on the assumption that ICU segmentation works properly for the languages we want to support. @gregtatum @nordzilla are you in touch with the ICU group? As far as I understand our plan it to use it for inference as well. Do you have any insights on the segmentation quality for CJK and other languages?

**Comment by ZJaume** [comment]
Updated the sentence split benchmark to add both versions of ICU4X. Seems that v1, despite not using any locale as an argument, its performance is almost equal.

https://docs.google.com/spreadsheets/d/1mGJ9MSyMlsK0EUDRC2J50uxApiti3ggnlrzAWn8rkMg/edit?gid=1851421209#gid=1851421209
