### ISSUE TITLE
Upload GCP experiments

### ISSUE THREAD

**Issue by eu9ene** [mozilla/translations#863]
Upload/reupload old experiments from GCP:
- Snakemake ones
- Taskcluster ones

**Comment by vrigal** [comment]
I published every GCP experiment I have from the `main` branch (https://github.com/mozilla/firefox-translations-training/commit/77479b3a77703a281bdf8313e168ecf697a376e5) to https://wandb.ai/teklia/projects.

**Comment by eu9ene** [comment]
@vrigal here are the two GCS buckets with the old experiments.

Snakemake: gs://releng-translations-dev
Taskcluster archive: gs://moz-fx-translations-data--303e-prod-translations-data

Let me double-check if some of those groups are still alive on Taskcluster and delete them from the moz-translations namespace. Then we can start re-uploading.
