### ISSUE TITLE
Do not use WMTNews as training!

### ISSUE THREAD

**Issue by ZJaume** [mozilla/translations#911]
The WMTNews corpus at OPUS is just a compilation of the WMT test sets, so it must not be included as training

https://github.com/mozilla/firefox-translations-training/blob/1f7ab70cd4dbb64e16bb6b38840490c2f2259cb0/configs/autogenerated/en-tr-spring-2024.yml#L79-L79

https://github.com/mozilla/firefox-translations-training/blob/1f7ab70cd4dbb64e16bb6b38840490c2f2259cb0/configs/autogenerated/en-ro-spring-2024.yml#L123

**Comment by eu9ene** [comment]
Great catch! We remove if in the find-corpus:

https://github.com/mozilla/firefox-translations-training/blob/1f7ab70cd4dbb64e16bb6b38840490c2f2259cb0/utils/find_corpus.py#L99

but it seems it got lost with all the refactorings and migration to the config generator... cc @gregtatum 

The outcome is quite sad as all our evaluation benchmarks for this cohort of languages are not correct

**Comment by eu9ene** [comment]
@marco-c FYI too

**Comment by eu9ene** [comment]
ok, maybe not all the results are incorrect but only the ones before 2019
